SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC 

SELECT *
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS C

SELECT *
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU

SELECT *
FROM sys.objects
WHERE type='P'

SELECT so.name
FROM sys.objects so
WHERE type='P'